applications/home/urls.py
from django import views
from django.urls import path
from . import views

app_name = 'home_app'

urlpatterns = [
    path('', views.HomeTemplateView.as_view(), name='home'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('terms/', views.TermsTemplateView.as_view(), name='terms'),
    path('privacy-policy/', views.PrivacyPolicyTemplatesView.as_view(), name='privacy_policy'),
    path('how-does-it-work/', views.HowDoesItWorkView.as_view(), name='how_work'),
]

applications/payments/urls.py
from django import views
from django.contrib import admin
from django.urls import path
from django.views.decorators.csrf import csrf_exempt
from . import views
from .views import WebhookStripeView

app_name = 'payments_app'

urlpatterns = [
    path('payments/', views.PaymentsView.as_view(), name='payments'),
    path('first-payment/', views.FirstPaymentView.as_view(), name='first_payment'),
    path('renewal-payment/<pk>/', views.VpsPaymentRenewalView.as_view(), name='vps_payment_renewal'),
    path('trader-payment/<pk>/', views.TraderPaymentRenewalView.as_view(), name='trader_payment'),
    path('checkout-session/', views.CheckoutSessionView.as_view(), name='checkout_session'),
    path('webhook-stripe/', csrf_exempt(WebhookStripeView.as_view()), name='webhook_stripe'),
]

applications/users/urls.py
from django import views
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'users_app'

urlpatterns = [
    path(
        'user-register/', 
        views.UserRegisterView.as_view(), 
        name='user_register'
        ),
    path(
        'user-login/', 
        views.UserLoginView.as_view(), 
        name='user_login'
        ),
    path(
        'logout/', 
        views.LogoutView.as_view(), 
        name='user_logout'
        ),
    path(
        'update-password/', 
        views.UpdatePasswordView.as_view(), 
        name='update_password'
        ),
    path(
        'code-verification/<pk>/', 
        views.CodeVerificationView.as_view(), 
        name='user_verification'
        ),
    path('email-password/', 
        views.RecoverAccountView.as_view(), 
        name='user_email_password'
        ),
    path(
        'change-password/<pk>/', 
        views.ChangePasswordView.as_view(), 
        name='user_change_password'
        ),
]

applications/vps/urls.py
from django import views
from django.urls import path
from . import views

app_name = 'vps_app'

urlpatterns = [
    path('panel-user/', views.PanelUserView.as_view(), name='panel_user'),
    path('add-account-mt5/', views.CreateAccounMt5View.as_view(), name='add_account_mt5'),
    path('delete-account-mt5/<pk>', views.DeleteAccountMt5View.as_view(), name='delete_account_mt5'),
    path('reconnect-account-mt5/>', views.ReconnectMt5Account.as_view(), name='reconnect_account_mt5'),
    path('confirmation-unsubscribe/', views.ConfirmationUnsubscribeView.as_view(), name='confirmation_unsubscribe'),
    path('unsubscribe/', views.UnsubscriberView.as_view(), name='unsubscribe'),
]

fortuna_303/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
#
from django.conf.urls import handler404
#
from applications.home.views import Error404View

urlpatterns = [
    path('admin/', admin.site.urls),
    # Incluimos las urls de las apps user, cuenta_mt5
    path('', include('applications.users.urls')),
    path('', include('applications.payments.urls')),
    path('', include('applications.vps.urls')),
    path('', include('applications.home.urls')),
]

handler404 = Error404View.as_view()

templates/includes/footer.html
{% load static %}

<!--Pie de pagina-->

<div class="box-footer">
    <footer class="footer">
        <a class="footer__link" href="{% url 'home_app:terms' %}">Terminos y Condiciones</a>
        <a class="footer__link" href="{% url 'home_app:privacy_policy' %}">Politica de privacidiad</a>
        <div class="footer__container">
            <h5>2024 Fortuna-303</h5>
            <h5>Created by Ronny Blandon</h5>
            <div class="linkedin">
                <img src="{% static 'img/Linkedin.svg' %}" alt="Linkedin">
                <a href="https://www.linkedin.com/in/ronnyblandon/">Linkedin</a>
            </div>
        </div>
    </footer>
</div>

templates/includes/header.html
{% load static %}

<!--menu-principal-->

<header class="box-menu">
    <nav class="menu">
        <button class="menu__btn-bars"><img src="{% static 'img/menu-bars.svg' %}" alt="menu-bars"></button>
    
        <a class="menu__link-logo" href="{% url 'home_app:home' %}">
            <img class="menu__img-logo" src="{% static 'img/logo.png' %}" alt="logo">
        </a>
    
        <ul class="menu__list">
            <li><a href="{% url 'home_app:home' %}">Inicio</a></li>
            <li><a href="{% url 'home_app:how_work' %}">¿Cómo funciona?</a></li>
            <li><a href="{% url 'home_app:contact' %}">Contacto</a></li>
        </ul>
    
        <ul class="menu__list-responsive">
            <li><a href="{% url 'home_app:home' %}">Inicio</a></li>
            <li><a href="{% url 'home_app:how_work' %}">¿Cómo funciona?</a></li>
            <li><a href="{% url 'home_app:contact' %}">Contacto</a></li>
        </ul>
    
        {% if not user.is_anonymous %}
        <ul class="menu__user menu__list ">
            <li><a href="{% url 'vps_app:panel_user' %}">Panel de Usuario</a></li>
            <li><a href="{% url 'payments_app:payments' %}">Pagos</a></li>
            <li><a href="{% url 'users_app:update_password' %}">Cambiar Contraseña</a></li>
            <li><a href="{% url 'users_app:user_logout' %}">Cerrar Sesión</a></li>
        </ul>

        <button class="menu__btn-profile">
            <img src="{% static 'img/menu-profile.svg' %}" alt="menu-profile">
        </button>
        {% else %}
        <a href="{% url 'users_app:user_login' %}">
            <button class="menu__btn-profile">
                <img src="{% static 'img/menu-profile.svg' %}" alt="menu-profile">
            </button>
        </a>
        {% endif %}
    </nav>
</header>

<script src="{% static 'js/menu.js' %}"></script>