applications/home/urls.py
from django import views
from django.urls import path
from . import views

app_name = 'home_app'

urlpatterns = [
    path('', views.HomeTemplateView.as_view(), name='home'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('terms/', views.TermsTemplateView.as_view(), name='terms'),
    path('privacy-policy/', views.PrivacyPolicyTemplatesView.as_view(), name='privacy_policy'),
    path('how-does-it-work/', views.HowDoesItWorkView.as_view(), name='how_work'),
]

applications/payments/urls.py
from django import views
from django.contrib import admin
from django.urls import path
from django.views.decorators.csrf import csrf_exempt
from . import views
from .views import WebhookStripeView

app_name = 'payments_app'

urlpatterns = [
    path('payments/', views.PaymentsView.as_view(), name='payments'),
    path('first-payment/', views.FirstPaymentView.as_view(), name='first_payment'),
    path('renewal-payment/<pk>/', views.VpsPaymentRenewalView.as_view(), name='vps_payment_renewal'),
    path('trader-payment/<pk>/', views.TraderPaymentRenewalView.as_view(), name='trader_payment'),
    path('checkout-session/', views.CheckoutSessionView.as_view(), name='checkout_session'),
    path('webhook-stripe/', csrf_exempt(WebhookStripeView.as_view()), name='webhook_stripe'),
]

fortuna_303/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
#
from django.conf.urls import handler404
#
from applications.home.views import Error404View

urlpatterns = [
    path('admin/', admin.site.urls),
    # Incluimos las urls de las apps user, cuenta_mt5
    path('', include('applications.users.urls')),
    path('', include('applications.payments.urls')),
    path('', include('applications.vps.urls')),
    path('', include('applications.home.urls')),
]

handler404 = Error404View.as_view()

applications/payments/models.py
from django.db import models
#Importamos los modelos
from applications.users.models import User
from applications.vps.models import AccountManagement
# importamos los managers
from .managers import VpsPaymentManager, TraderPaymentManager

# creamos una tupla con los estados de pago para el atributo status
payment_status = (('Pagar', 'No Pagado'), ('Pagado', 'Pagado'), ('Cancelado', 'Cancelado'), ('Reembolsado', 'Reembolsado'))
payment_methods = (('Paypal', 'Paypal'), ('Stripe', 'Stripe'))

class VpsPayment(models.Model):
    created_date = models.DateField('Fecha de creación', max_length=20)
    expiration = models.DateField('Fecha de vencimiento', max_length=20)
    total = models.DecimalField('Total', max_digits=9, decimal_places=2)
    status = models.CharField('Estado', max_length=12, choices=payment_status)
    id_user = models.ForeignKey(User, on_delete=models.CASCADE)
    payment_method = models.CharField('Metodo de Pago', max_length=20, blank=True, choices=payment_methods)
    transaction_id = models.CharField('ID Transacción', max_length=50, blank=True)
    
    objects = VpsPaymentManager()

    def __str__(self):
        return str(self.id) + ' - ' +  str(self.created_date) + ' - ' + str(self.expiration) + ' - ' + self.status


class TraderPayment(models.Model):
    created_date = models.DateField('Fecha de creación')
    expiration = models.DateField('Fecha de creación')
    id_management = models.ForeignKey(AccountManagement, on_delete=models.CASCADE)
    total = models.DecimalField('Total', max_digits=9, decimal_places=2)
    status = models.CharField('Estado', max_length=12, choices=payment_status)
    id_user = models.ForeignKey(User, on_delete=models.CASCADE)
    payment_method = models.CharField('Metodo de Pago', max_length=20, blank=True, choices=payment_methods)
    transaction_id = models.CharField('ID Transacción', max_length=30, blank=True)

    objects = TraderPaymentManager()

    def __str__(self):
        return str(self.id)+' - '+str(self.created_date)+' - '+str(self.expiration)+' - '+self.status+str(self.total)

applications/payments/views.py
from datetime import datetime
import stripe
from django.views.generic import View, TemplateView, DetailView
from django.http.response import JsonResponse, HttpResponseRedirect, HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.urls import reverse_lazy, reverse
from django.core.paginator import Paginator
# importamos los modelos
from .models import TraderPayment, VpsPayment
from applications.users.models import User
from applications.vps.models import AccountMt5
#importamos funciones
from .functions import enable_reconnection_mt5, expiration_vps
from .paypal import create_order_paypal, create_renewal_order_paypal, capture_order_paypal
from .stripe import create_order_stripe, create_renewal_order_stripe
from applications.vps.functions import active_buttons_time
from fortuna_303.settings.base import get_secret
from applications.users.function import notification_admin_by_mail, create_mail
# Create your views here.

class PaymentsView(LoginRequiredMixin, TemplateView):
    template_name = 'payments/payments.html'
    login_url = reverse_lazy('users_app:user_login')

    def get(self, request, *args, **kwargs):
        # Traemos la instancia del usuario relacionado a la nueva factura
        user = User.objects.get(id=request.user.id)

        # Recogemos las variables de la url que nos devuelve paypal al cancelar o aprobar el pago
        token = self.request.GET.get('token')
        if token:
            details = capture_order_paypal(token)
            if details:
                # Verificamos si es un primer pago del servicio de VPS y COPYTRADING
                if details['custom_id'] == 'first_payment':
                    User.objects.filter(id=request.user.id).update(subscriber=True)
                    payment = VpsPayment.objects.save_payment_vps(details['amount'], user, 'Paypal', details['id'])
                    messages.add_message(request=self.request, level=messages.SUCCESS, message='Su pago fue procesado exitosamente.')
                    
                    #Enviar un correo del importe al usuario cuando el pago haya sido procesado con exito.
                    mail = create_mail(user.email, f"FORTUNA 303 IMPORTE DE VPS+COPYTRADING #{payment.id}", "payments/invoice.html", {"id_payment": payment.id, "name": user.name +" "+ user.last_name, "status": payment.status, "service": "VPS+COPYTRADING", "created_date": payment.created_date, "expiration": payment.expiration, "price": payment.total})
                    mail.send(fail_silently=False)
                    #Enviar un correo de notificacion al admin cuando el pago haya sido procesado con exito.
                    affair_admin = "NUEVO PAGO DE VPS+COPYTRADING RECIBIDO."
                    message_admin = f"EL pago recibido es del usario:\n\n ID: {user.id}\n name: {user.name} {user.last_name}\n correo: {user.email}\n\nLos datos del importe:\n\n ID: {payment.id}\n Created date: {payment.created_date}\n Expiration: {payment.expiration}\n Total: {payment.total}\n Status: {payment.status}\n Method: {payment.payment_method}\n ID_Transaction: {payment.transaction_id}"
                    notification_admin_by_mail(affair_admin, message_admin)

                else:
                    # Convertimos el string del valor de custom_id a un dict
                    dictionary = eval((details['custom_id']))
                    
                    # Verificamos si es una renovacion del servicio VPS o un pago para el trader
                    if 'vps' in dictionary:
                        id_payment = dictionary['vps']
                        payment = VpsPayment.objects.update_payment_vps(id_payment, 'Paypal', details['id'])
                        messages.add_message(request=self.request, level=messages.SUCCESS, message='Su pago fue procesado exitosamente.')
                        
                        #Enviar un correo del importe al usuario cuando el pago haya sido procesado con exito.
                        mail = create_mail(user.email, f"FORTUNA 303 IMPORTE DE VPS+COPYTRADING #{payment.id}", "payments/invoice.html", {"id_payment": payment.id, "name": user.name +" "+ user.last_name, "status": payment.status, "service": "VPS+COPYTRADING", "created_date": payment.created_date, "expiration": payment.expiration, "price": payment.total})
                        mail.send(fail_silently=False)
                        #Enviar un correo de notificacion al admin cuando el pago haya sido procesado con exito.
                        affair_admin = "NUEVO PAGO DE VPS+COPYTRADING RECIBIDO."
                        message_admin = f"EL pago recibido es del usario:\n\n ID: {user.id}\n name: {user.name} {user.last_name}\n correo: {user.email}\n\nLos datos del importe:\n\n ID: {payment.id}\n Created date: {payment.created_date}\n Expiration: {payment.expiration}\n Total: {payment.total}\n Status: {payment.status}\n Method: {payment.payment_method}\n ID_Transaction: {payment.transaction_id}"
                        notification_admin_by_mail(affair_admin, message_admin)

                        # Verificamos si la cuenta esta desconectada
                        try:
                            account_mt5 = AccountMt5.objects.get(id_user=user.id)
                            if account_mt5.status == '0':
                                trader_payment = TraderPayment.objects.unpaid_trader_payments(user.id)
                                vps_payment = VpsPayment.objects.unpaid_vps_payments(user.id)
                                # Conectamos la cuenta mt5 de nuevo a metaapi en caso de que este desconectado y este al dia con los pagos
                                if trader_payment == False and vps_payment == False:
                                    enable_reconnection_mt5(user.id, self.request)
                        except Exception as err:
                            messages.add_message(request=self.request, level=messages.WARNING, message='Hubo un error al intentar habilitar la reconexión de la cuenta mt5.')
                            print("Hubo un error al intentar habilitar la reconexión de la cuenta mt5 del usuario a metaapi. ", err)

                    elif 'trader' in dictionary:
                        id_payment = dictionary['trader']
                        payment = TraderPayment.objects.update_payment_trader(id_payment, 'Paypal', details['id'])
                        messages.add_message(request=self.request, level=messages.SUCCESS, message='Su pago fue procesado exitosamente.')
                        
                        #Enviar un correo del importe al usuario cuando el pago haya sido procesado con exito.
                        mail = create_mail(user.email, f"FORTUNA 303 IMPORTE DE GESTIÓN DE CUENTAS MT5 #{payment.id}", "payments/invoice.html", {"id_payment": payment.id, "name": user.name +" "+ user.last_name, "status": payment.status, "service": "GESTIÓN DE CUENTAS MT5", "created_date": payment.created_date, "expiration": payment.expiration, "id_management": payment.id_management.id, "price": payment.total})
                        mail.send(fail_silently=False)
                        #Enviar un correo de notificacion al admin cuando el pago haya sido procesado con exito.
                        affair_admin = "NUEVO PAGO DE GESTIÓN DE CUENTAS MT5 RECIBIDO."
                        message_admin = f"EL pago recibido es del usario:\n\n ID: {user.id}\n name: {user.name} {user.last_name}\n correo: {user.email}\n\nLos datos del importe:\n\n ID: {payment.id}\n Created date: {payment.created_date}\n Expiration: {payment.expiration}\n Id_management: {payment.id_management.id}\n Total: {payment.total}\n Status: {payment.status}\n Method: {payment.payment_method}\n ID_Transaction: {payment.transaction_id}"
                        notification_admin_by_mail(affair_admin, message_admin)
                        
                        # Verificamos si la cuenta esta desconectada
                        try: 
                            account_mt5 = AccountMt5.objects.get(id_user=user.id)
                    
                            if account_mt5.status == '0':
                                trader_payment = TraderPayment.objects.unpaid_trader_payments(user.id)
                                vps_payment = VpsPayment.objects.unpaid_vps_payments(user.id)
                                # Conectamos la cuenta mt5 de nuevo a metaapi en caso de que este desconectado y este al dia con los pagos
                                if trader_payment == False and vps_payment == False:
                                    enable_reconnection_mt5(user.id, self.request)
                        except Exception as err:
                            messages.add_message(request=self.request, level=messages.WARNING, message='Hubo un error al intentar habilitar la reconexión de la cuenta mt5.')
                            print("Hubo un error al intentar habilitar la reconexión de la cuenta mt5 del usuario a metaapi. ", err)

        context = self.get_context_data(**kwargs)
        return self.render_to_response(context)


    def get_context_data(self, **kwargs):
        context = super(PaymentsView, self).get_context_data(**kwargs)

        id_user = self.request.user.id # sacamos el id del usuario

        vps_payment = VpsPayment.objects.vps_payments_by_user(id_user)
        paginator1 = Paginator(vps_payment, 10)
        page = self.request.GET.get('page')
        context['vps_payments'] = paginator1.get_page(page)
        context['vps_payments_pages'] = paginator1.num_pages

        trader_payment = TraderPayment.objects.trader_payments_by_user(id_user)
        paginator2 = Paginator(trader_payment, 10)
        page2 = self.request.GET.get('page2')
        context['trader_payments'] = paginator2.get_page(page2)

templates/payments/first-payment.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Panel Usuario {% endblock title %}

{% block css %} {% static 'css/details-payment.css' %} {% endblock css %}

{% block content %}
{% include 'includes/header.html' %}

<!--Titulo de la pagina-->

<h1 class="title">Detalles de pago</h1>

<!-- Mensajes de exito o de error -->

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>  
    {% endfor %}
</ul>
{% endif %}

<!-- Sección de detalles de pago -->
<div class="box-general">
    <div class="details-payment">
        <div class="details-payment-child">
            <h3>Fecha: </h3>
            <p>{{ detail_payment.now|date:"d-M-Y" }}</p>
        </div>
        <div class="details-payment-child">
            <h3>Expiración:</h3>
            <p>{{ detail_payment.expiration|date:"d-M-Y" }}</p>
        </div>
        <div class="details-payment-child">
            <h3>Precio:</h3>
            <p>${{ detail_payment.price }}</p>
        </div>
        <div class="details-payment-description">
            <h3>Descripción:</h3> 
            <p>Servicio mensual de vps para metatrader 5 y uso del sistema copytrading.</p>
        </div>
    </div>

    <!-- Sección de metodos de pago -->
    <div class="method-payment">
        <h2>Metodos de pago</h2>

        <div class="container-methods">
            <form id="form-payment" action="{% url 'payments_app:checkout_session' %}" method="post"> {% csrf_token %}
                <input type="hidden" name="type" value="first-payment">
                <label class="label-radio-paypal">
                    <input id="paypal" type="radio" name="payment-method" value="paypal" required>Paypal<br>
                </label>
                <label class="label-radio-stripe">
                    <input id="stripe" type="radio" name="payment-method" value="stripe" required>Tarjeta de Crédito o Débito<br>
                </label>
                <label class="input-checkbox">
                <h5>
                    <input type="checkbox" name="terms-and-conditions" value="True" required>
                    He leído y estoy de acuerdo con los <a href='{% url 'home_app:terms' %}'>términos y condiciones</a> de fortuna303.
                </h5>
                </label>
                <button class="button-payment" type="submit">Realizar pago</button>
            </form>
        </div>
    </div>
</div>

<script src="{% static 'js/details-payment.js' %}"></script>

{% include 'includes/footer.html' %}
{% endblock content %}

templates/payments/payments.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Panel Usuario {% endblock title %}

{% block css %} {% static 'css/payments.css' %} {% endblock css %}

{% block content %}
{% include 'includes/header.html' %}

<!--Titulo de la pagina-->

<h1 class="title">Pagos</h1>

<!-- Mensajes de exito o de error -->

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>  
    {% endfor %}
</ul>
{% endif %}

<!--Contenido del Panel de Usuario-->
<div class="box-general-accordion">

    <!-- Sección de facturación de Servicio del trader de la cuenta madre para moviles -->

    <section class="box-accordion">
        <h2 class="box-title">Gestión de Cuentas mt5 (semana)</h2>
        <details class="primary-details">
            <summary><span>ID pago</span><span>Estado</span></summary>
        </details>
        {% if trader_payments.paginator.count > 0 %}
        {% for payment in trader_payments %}
        <div class="box-detail">
            <details class="details">
                <summary>
                    <span>{{ payment.id }}</span>
                    {% if payment.status == "Pagar" %}
                    <a class="btn-pay" href="{% url 'payments_app:trader_payment' payment.id %}">{{ payment.status }}</a>
                    {% else %}
                    {{ payment.status }}
                    {% endif %}
                </summary>
                <ul>
                    <li><h4 class="title-celdas">Fecha:</h4><span>{{ payment.created_date|date:"Y-m-d" }}</span></li>
                    <li><h4 class="title-celdas">Vecimiento</h4><span>{{ payment.expiration|date:"Y-m-d" }}</span></li>
                    <li><h4 class="title-celdas">Id. Referencia</h4><span>{{ payment.id_management.id }}</span></li>
                    <li><h4 class="title-celdas">Total:</h4><span>{{ payment.total }}</span></li>
                </ul>
            </details>
        </div>
        {% endfor %}
        {% endif %}

        <!-- Bloque de paginación para la Tabla mobile de pagos de GESTION DE CUENTAS MT5 -->
        <div>
            {% if trader_payments.paginator.num_pages > 1 %}
            <nav id="paginator">
                <button class="link-page4 link-page-first" value="1">&laquo;</button>
                <button class="link-page4 link-page-previous" value="1">&lsaquo;</button>
                <!--Limitamos la cantidad de botones en el paginador hasta 12 botones incluyendo los 
                botones de retroceder y avanzar para que no se deforme en los dispositivos moviles-->
                {% if trader_payments.paginator.num_pages >= 8 %}
                    {% for pagina in range %}
                    {% if pagina == trader_payments.number %}
                <button class="link-page4 link-page-current" value="{{pagina}}">{{ pagina }}</button>
                    {% else %}
                <button class="link-page4" value="{{pagina}}">{{ pagina }}</button>
                    {% endif %}
                    {% endfor %}
                {% else %}
                    {% for pagina in trader_payments.paginator.page_range %}
                    {% if pagina == trader_payments.number %}
                <button class="link-page4 link-page-current" value="{{pagina}}">{{ pagina }}</button>
                    {% else %}
                <button class="link-page4" value="{{pagina}}">{{ pagina }}</button>
                    {% endif %}
                    {% endfor %}
                {% endif %}
                <button class="link-page4 link-page-next" value="2">&rsaquo;</button>
                <button class="link-page4 link-page-last" value="9">&raquo;</button>
            </nav>
            {% endif %}
        </div>
    </section>

    <!-- Sección de facturación de sistema copytrading y VPS para Moviles-->

    <section class="box-accordion-2">
        <h2 class="box-title">Vps + Copytrading (mes)</h2>
        {% if not user.subscriber %}
        <a class="link-first-payment" href="{% url 'payments_app:first_payment' %}">Adquirir vps + sistema copytrading</a>
        {% endif %}
        <details class="primary-details-2">
            <summary><span>ID pago</span><span>Estado</span></summary>
        </details>
        {% for payment in vps_payments %}
        <div class="box-detail-2">
            <details class="details-2">
                <summary>
                    <span>{{ payment.id }}</span>
                    {% if payment.status == "Pagar" %}
                    <a class="btn-pay" href="{% url 'payments_app:vps_payment_renewal' payment.id %}">{{ payment.status }}</a>
                    {% else %}
                    {{ payment.status }}
                    {% endif %}
                </summary>
                <ul>
                    <li><h4 class="title-celdas">Fecha</h4><span>{{ payment.created_date|date:"Y-m-d" }}</span></li>
                    <li><h4 class="title-celdas">Vecimiento</h4><span>{{ payment.expiration|date:"Y-m-d" }}</span></li>
                    <li><h4 class="title-celdas">Total</h4><span>{{ payment.total }}</span></li>
                </ul>
            </details>
        </div>
        {% endfor %}

        <!-- Bloque de paginación para la Tabla mobile de pagos de VPS + COPYTRADING  -->
        <div>
            {% if vps_payments.paginator.num_pages > 1 %}
            <nav id="paginator">
                <button class="link-page3 link-page-first" value="1">&laquo;</button>
                <button class="link-page3 link-page-previous" value="1">&lsaquo;</button>
                <!--Limitamos la cantidad de botones en el paginador hasta 12 botones incluyendo los 
                botones de retroceder y avanzar para que no se deforme en los dispositivos moviles-->
                {% if vps_payments.paginator.num_pages >= 8 %}
                    {% for pagina in range %}
                    {% if pagina == vps_payments.number %}
                <button class="link-page3 link-page-current" value="{{pagina}}">{{ pagina }}</button>
                    {% else %}
                <button class="link-page3" value="{{pagina}}">{{ pagina }}</button>
                    {% endif %}
                    {% endfor %}
                {% else %}
                    {% for pagina in vps_payments.paginator.page_range %}
                    {% if pagina == vps_payments.number %}
                <button class="link-page3 link-page-current" value="{{pagina}}">{{ pagina }}</button>
                    {% else %}
                <button class="link-page3" value="{{pagina}}">{{ pagina }}</button>
                    {% endif %}
                    {% endfor %}
                {% endif %}
                <button class="link-page3 link-page-next" value="2">&rsaquo;</button>
                <button class="link-page3 link-page-last" value="9">&raquo;</button>
            </nav>
            {% endif %}
        </div>
    </section>

    <!-- HTML para mostrar en tablet y pc de escritorio -->
    <!-- Sección de tabla de facturas de servicio de gestión de cuentas -->

    <section class="box-invoices">
        <h2 class="box-title">Gestión de Cuentas mt5 (Semana)</h2>
        <div>
            <table class="invoice-table">
                <tr>
                    <th>ID</th>
                    <th>Fecha</th>
                    <th>Vencimiento</th>
                    <th>Id. Referencia</th>
                    <th>Total</th>
                    <th>Estado</th>
                </tr>
                {% if trader_payments.paginator.count > 0 %}
                {% for payment in trader_payments %}
                <tr class="rows-trader-payment">
                    <td>{{ payment.id }}</td>
                    <td>{{ payment.created_date|date:"Y-m-d" }}</td>
                    <td>{{ payment.expiration|date:"Y-m-d" }}</td>
                    <td>{{ payment.id_management.id }}</td>
                    <td>{{ payment.total }}</td>
                    <td>
                        {% if payment.status == "Pagar" %}
                        <a class="btn-pay" href="{% url 'payments_app:trader_payment' payment.id %}">{{ payment.status }}</a>
                        {% else %}
                        {{ payment.status }}
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
                {% endif %}
            </table>
        </div>

        <!-- Bloque de paginación para la Tabla de pagos de GESTION DE CUENTA MT5  -->
        <div>
            {% if trader_payments.paginator.num_pages > 1 %}
            <nav id="paginator">
                <button class="link-page2 link-page-first" value="1">&laquo;</button>
                <button class="link-page2 link-page-previous" value="1">&lsaquo;</button>
                <!--Limitamos la cantidad de botones en el paginador hasta 12 botones incluyendo los 
                botones de retroceder y avanzar para que no se deforme en los dispositivos moviles-->
                {% if trader_payments.paginator.num_pages >= 8 %}
                    {% for pagina in range %}
                    {% if pagina == trader_payments.number %}
                <button class="link-page2 link-page-current" value="{{pagina}}">{{ pagina }}</button>
                    {% else %}
                <button class="link-page2" value="{{pagina}}">{{ pagina }}</button>
                    {% endif %}
                    {% endfor %}
                {% else %}
                    {% for pagina in trader_payments.paginator.page_range %}
                    {% if pagina == trader_payments.number %}
                <button class="link-page2 link-page-current" value="{{pagina}}">{{ pagina }}</button>
                    {% else %}
                <button class="link-page2" value="{{pagina}}">{{ pagina }}</button>
                    {% endif %}
                    {% endfor %}
                
                {% endif %}

                <button class="link-page2 link-page-next" value="2">&rsaquo;</button>
                <button class="link-page2 link-page-last" value="9">&raquo;</button>
            </nav>
            {% endif %}
        </div>
    </section>

    <!-- Sección de tabla de facturas de vps y copytrading -->

    <section class="box-invoices">
        <h2 class="box-title">VPS + Copy-trading (Mes)</h2>
        {% if not user.subscriber %}
        <a class="link-first-payment" href="{% url 'payments_app:first_payment' %}">Adquirir vps + sistema copytrading</a>
        {% endif %}
        <div>
            <table class="invoice-table">
                <tr class="table-header">
                    <th>ID</th>
                    <th>Fecha</th>
                    <th>Vecimiento</th>
                    <th>Total</th>
                    <th>Estado</th>
                </tr>
                {% for payment in vps_payments %}
                <tr class="rows-vps-payment">
                    <td>{{ payment.id }}</td>
                    <td>{{ payment.created_date|date:"Y-m-d" }}</td>
                    <td>{{ payment.expiration|date:"Y-m-d" }}</td>
                    <td>{{ payment.total }}</td>
                    <td>
                        {% if payment.status == "Pagar" %}
                        <a class="btn-pay" href="{% url 'payments_app:vps_payment_renewal' payment.id %}">{{ payment.status }}</a>
                        {% else %}
                        {{ payment.status }}
                        {% endif %}
                    </td>
                </tr>    
                {% endfor %}
            </table>
        </div>

        <!-- Bloque de paginación para la Tabla de pagos de VPS + COPYTRADING  -->
        <div>
            {% if vps_payments.paginator.num_pages > 1 %}
            <nav id="paginator">
                <button class="link-page link-page-first" value="1">&laquo;</button>
                <button class="link-page link-page-previous" value="1">&lsaquo;</button>
                <!--Limitamos la cantidad de botones en el paginador hasta 12 botones incluyendo los 
                botones de retroceder y avanzar para que no se deforme en los dispositivos moviles-->
                {% if vps_payments.paginator.num_pages >= 8 %}
                {% for pagina in range %}
                    {% if pagina == vps_payments.number %}
                <button class="link-page link-page-current" value="{{pagina}}">{{ pagina }}</button>
                    {% else %}
                <button class="link-page" value='{{pagina}}'>{{ pagina }}</button>
                    {% endif %}
                    {% endfor %}
                {% else %}
                    {% for pagina in vps_payments.paginator.page_range %}
                    {% if pagina == vps_payments.number %}
                <button class="link-page link-page-current" value="{{pagina}}">{{ pagina }}</button>
                    {% else %}
                <button class="link-page" value='{{pagina}}'>{{ pagina }}</button>
                    {% endif %}
                    {% endfor %}
                {% endif %}
                <button class="link-page link-page-next" value="2">&rsaquo;</button>
                <button class="link-page link-page-last" value="9">&raquo;</button>
            </nav>
            {% endif %}
        </div>
    </section>
</div>

<script src="{% static 'js/accordion.js' %}" type="module"></script>
<script src="{% static 'js/payments.js' %}" type="module"></script>

{% include 'includes/footer.html' %}
{% endblock content %}