applications/users/urls.py
from django import views
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'users_app'

urlpatterns = [
    path(
        'user-register/', 
        views.UserRegisterView.as_view(), 
        name='user_register'
        ),
    path(
        'user-login/', 
        views.UserLoginView.as_view(), 
        name='user_login'
        ),
    path(
        'logout/', 
        views.LogoutView.as_view(), 
        name='user_logout'
        ),
    path(
        'update-password/', 
        views.UpdatePasswordView.as_view(), 
        name='update_password'
        ),
    path(
        'code-verification/<pk>/', 
        views.CodeVerificationView.as_view(), 
        name='user_verification'
        ),
    path('email-password/', 
        views.RecoverAccountView.as_view(), 
        name='user_email_password'
        ),
    path(
        'change-password/<pk>/', 
        views.ChangePasswordView.as_view(), 
        name='user_change_password'
        ),
]

fortuna_303/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
#
from django.conf.urls import handler404
#
from applications.home.views import Error404View

urlpatterns = [
    path('admin/', admin.site.urls),
    # Incluimos las urls de las apps user, cuenta_mt5
    path('', include('applications.users.urls')),
    path('', include('applications.payments.urls')),
    path('', include('applications.vps.urls')),
    path('', include('applications.home.urls')),
]

handler404 = Error404View.as_view()

applications/users/models.py
from django.db import models
# importamos las librerias para el control de usuarios
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
# imporatmos managers
from .managers import UserManager

class Level(models.Model):
    account_level = models.CharField('Nivel', max_length=20)
    min_balance = models.DecimalField('Balance Minimo', max_digits=10, decimal_places=2)
    max_balance = models.DecimalField('Balance Maximo', max_digits=10, decimal_places=2)
    price = models.DecimalField('Precio', max_digits=6, decimal_places=2)

    def __str__(self):
        return str(self.id) + ' - ' + self.account_level + ' ' + str(self.max_balance) + ' - ' + str(self.price)


class User(AbstractBaseUser, PermissionsMixin):
    
    name = models.CharField('Nombre', max_length=20)
    last_name = models.CharField('Apellido', max_length=20)
    email = models.EmailField('Correo Electronico', max_length=60, unique=True)
    level = models.ForeignKey(Level, on_delete=models.CASCADE)
    subscriber = models.BooleanField('Suscriptor')
    due_payments = models.BooleanField('¿Tiene pagos vencidos?')
    id_customer_stripe = models.CharField('ID customer stripe', max_length=25, blank=True, null=True)
    validation_code = models.CharField(max_length=6)
    # creamos la columna staff en modelo para la creacion de superusuarios
    is_staff = models.BooleanField(default=False)
    # nueva columna para verificar si el correo es real
    is_active = models.BooleanField(default=False)

    class Meta:
        unique_together = ('email',)
    
    USERNAME_FIELD = 'email'

    REQUIRED_FIELDS = ['name', 'last_name']

    objects = UserManager()

    def __str__(self):
        return str(self.id) + ' - ' + self.name + ' ' + self.last_name + ' - ' + self.email

    def get_full_name(self):
        return self.first_name + " " + self.last_name

applications/users/views.py
from django.core.mail import send_mail
# importamos las vistas genericas
from django.views.generic import View
from django.views.generic.edit import FormView
# importamos las librerias de redireccion de urls
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect
# importamos las librerias de autenticacion de django
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
# importamos los forms
from .forms import (
    UserRegisterForm, UserLoginForm, UpdatePasswordForm, VerificationForm, 
    EmailPasswordForm, ChangePasswordForm
)
# importamos los modelos
from .models import User, Level
# imporatmos function.py
from .function import code_generator, notification_admin_by_mail, create_mail


class UserRegisterView(FormView):
    template_name = 'users/register.html'
    form_class = UserRegisterForm
    success_url = reverse_lazy('users_app:user_login')

    def form_valid(self, form):
        # Generamos el codigo de verificacion de correo al usuario recien registrado
        codigo = code_generator()
        # este get devuelve una tupla de instancias
        level = Level.objects.get(account_level='0'), # Siempre iniciaran como nivel 0
        
        name = form.cleaned_data['name']
        last_name = form.cleaned_data['last_name']
        email = form.cleaned_data['email']
        user = User.objects.create_user(
            name,
            last_name,
            email,
            level[0],
            form.cleaned_data['password1'],
            validation_code=codigo
        )

        # Enviamos el codigo de verificar cuenta al email del usuario
        mail = create_mail(user.email, "CÓDIGO DE VERIFICACIÓN", "users/send-verification.html", {"validation_code": codigo, "message_context": "Necesitas este código para verificar el correo electrónico."})
        mail.send(fail_silently=False)
        # Enviamos un correo notificando al email del administrador que se ha creado una cuenta de usuario.
        affair_admin = "NUEVA CUENTA DE USUARIO."
        message_admin = f"Se ha creado una nueva cuenta de usuario sin verificar. \n\n ID: {user.id} \n Name: {name} {last_name} \n Email: {email}"
        notification_admin_by_mail(affair_admin, message_admin)

        # Redirigimos a pantalla de verificacion al usuario
        return HttpResponseRedirect(
            reverse('users_app:user_verification', kwargs={'pk': user.id})
        )


class UserLoginView(FormView):
    template_name = 'users/login.html'
    form_class = UserLoginForm
    success_url = reverse_lazy('vps_app:panel_user')

    def form_valid(self, form):
        user = authenticate(
            email=form.cleaned_data['email'],
            password=form.cleaned_data['password']
        )
        login(self.request, user)

        return super(UserLoginView, self).form_valid(form)


class LogoutView(View):

    def get(self, request, *args, **kwargs):
        logout(request)
        return HttpResponseRedirect(
            reverse('users_app:user_login')
        )

# esta vista es para cambiar la contraseña de los usuarios logueados
class UpdatePasswordView(LoginRequiredMixin, FormView):
    template_name = 'users/update-password.html'
    form_class = UpdatePasswordForm
    success_url = reverse_lazy('users_app:user_login')
    login_url = reverse_lazy('users_app:user_login')

    def get_form_kwargs(self):
        kwargs = super(UpdatePasswordView, self).get_form_kwargs()
        kwargs.update({
            'email': self.request.user.email
        })
        return kwargs

    def form_valid(self, form):

        usuario = self.request.user
        user = authenticate(
            email=usuario.email,
            password=form.cleaned_data['password3']
        )

        if user:
            new_password = form.cleaned_data['password1']
            usuario.set_password(new_password)
            usuario.save()

        messages.add_message(request=self.request, level=messages.SUCCESS, message='Se ha cambiado la contraseña, inicie sesión.')

        # Enviamos un correo notificando al email del administrador que se ha creado una cuenta de usuario.
        affair_admin = "USUARIO HA CAMBIADO SU CONTRASEÑA."
        message_admin = f"Un usuario ha cambiado su contraseña. \n\n ID: {user.id} \n Name: {user.name} {user.last_name} \n Email: {user.email}"
        notification_admin_by_mail(affair_admin, message_admin)

        logout(self.request)

        return super(UpdatePasswordView, self).form_valid(form)


class CodeVerificationView(FormView):
    template_name = 'users/code-verification.html'
    form_class = VerificationForm
    success_url = reverse_lazy('users_app:user_login')

    # Reescribimos esta funcion para pasarle el pk al Formulario desde la View
    def get_form_kwargs(self):
        kwargs = super(CodeVerificationView, self).get_form_kwargs()
        kwargs.update({
            'pk': self.kwargs['pk']
        })
        return kwargs

    def form_valid(self, form):

        user = User.objects.filter(
            id=self.kwargs['pk']
        )
        user.update(is_active=True)
        messages.add_message(request=self.request, level=messages.SUCCESS, message='Se ha verificado el correo electrónico, ya puede iniciar sesión.')

        # Enviamos un correo notificando al email del administrador que se ha verificado una cuenta de usuario.
        affair_admin = "SE HA VERIFICADO UNA CUENTA DE USUARIO"
        message_admin = f"Se verifico la cuenta del usuario. \n\n ID: {user[0].id} \n Name: {user[0].name} {user[0].last_name} \n Email: {user[0].email}"
        notification_admin_by_mail(affair_admin, message_admin)

        return super(CodeVerificationView, self).form_valid(form)


class RecoverAccountView(FormView):
    template_name = 'users/forgot-password.html'
    form_class = EmailPasswordForm
    success_url = reverse_lazy('users_app:user_change_password')

    def get_queryset(self):
        queryset = super(RecoverAccountView, self).get_queryset()
        queryset = queryset.id
        return queryset

    def form_valid(self, form):
        # Generamos el codigo de verificacion al correo del usuario que olvido su contraseña
        codigo = code_generator()

        # El metodo form.cleaned_data no recibe el dato por lo que usamos el self.request.POST.get
        email = form.cleaned_data['email']

        # Actualizamos el nuevo codigo al usuario en la base de datos
        user = User.objects.filter(email=email)
        user.update(validation_code=codigo)
        id_user = user[0].id # obtenemos el id del usuario

        # Enviamos el codigo de verificación para cambiar contraseña al usuario
        mail = create_mail(user[0].email, "RECUPERACIÓN DE CUENTA", "users/send-verification.html", {"validation_code": codigo, "message_context": "Necesitas este código para cambiar la contraseña."})
        mail.send(fail_silently=False)

        # Redirigimos a pantalla de verificacion al usuario para cambiar contraseña
        return HttpResponseRedirect(
            reverse('users_app:user_change_password', kwargs={'pk': id_user})
        )


# esta vista es para cambiar la contraseña de los usuarios que no estan logueados
class ChangePasswordView(FormView):
    template_name = 'users/change-password.html'
    form_class = ChangePasswordForm
    success_url = reverse_lazy('users_app:user_login')

    # Reescribimos esta funcion para pasarle el pk al Formulario desde la View
    def get_form_kwargs(self):
        kwargs = super(ChangePasswordView, self).get_form_kwargs()
        kwargs.update({
            'pk': self.kwargs['pk']
        })
        return kwargs

    def form_valid(self, form):
        
        user = User.objects.filter(validation_code=form.cleaned_data['validation_code'])
        user = user.get()
        new_password = self.request.POST.get('password2')
        user.set_password(new_password)
        user.save()
        messages.add_message(request=self.request, level=messages.SUCCESS, message='Se ha cambiado la contraseña, inicie sesión.')

        # Enviamos un correo notificando al email del administrador que se ha creado una cuenta de usuario.
        affair_admin = "USUARIO HA CAMBIADO SU CONTRASEÑA."
        message_admin = f"Un usuario ha cambiado su contraseña. \n\n ID: {user.id} \n Name: {user.name} {user.last_name} \n Email: {user.email}"
        notification_admin_by_mail(affair_admin, message_admin)

        return super(ChangePasswordView, self).form_valid(form)
        

templates/users/change-password.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Cambiar contraseña {% endblock title %}

{% block css %} {% static 'css/register.css' %} {% endblock css %}

{% block content %}
{% include 'includes/header.html' %}

<!--Titulo de la pagina-->

<h1 class="title">Cambiar contraseña</h1>

<!--Formulario de registro-->
    
<div class="container-form">
    <form class="form-register" method="post"> {% csrf_token %}
    
        <hr>
        
        {{ form.non_field_errors }}
        <div class="form__container">
            <p>Ingrese el código de verificación que se le envió a su correo electrónico.</p>
        </div>

        <label class="form-register__label"><img src="{% static 'img/icono-contraseña.svg' %}" alt="icono-contraseña">
            {{form.validation_code}}</label>
        
        {{form.password2.errors}}
        <label class="form-register__label"><img src="{% static 'img/icono-contraseña.svg' %}" alt="icono-contraseña">
            {{form.password1}}</label>

        <label class="form-register__label"><img src="{% static 'img/icono-contraseña.svg' %}" alt="icono-contraseña">
            {{form.password2}}</label>

        <input class="form-register__input-submit" type="submit" value="Cambiar Contraseña">
    
        <hr>
    </form>
</div class="container-form">

{% include 'includes/footer.html' %}
{% endblock content %}

templates/users/code-verification.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Cambiar contraseña {% endblock title %}

{% block css %} {% static 'css/register.css' %} {% endblock css %}

{% block content %}
{% include 'includes/header.html' %}

<!--Titulo de la pagina-->

<h1 class="title">Cambiar contraseña</h1>

<!--Formulario de registro-->
    
<div class="container-form">
    <form class="form-register" method="post"> {% csrf_token %}
    
        <hr>
        {{ form.non_field_errors }}
        {{form.validation_code.errors}}
        <div class="form__container">
            <p>Ingrese su código de verificación que se le envió a su correo electrónico.</p>
        </div>
        
        <label class="form-register__label"><img src="{% static 'img/icono-contraseña.svg' %}" alt="icono-contraseña">
            {{form.validation_code}}</label>


        <input class="form-register__input-submit" type="submit" value="Verificar">
    
        <hr>
    </form>
</div class="container-form">

{% include 'includes/footer.html' %}
{% endblock content %}

templates/users/forgot-password.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Recuperar cuenta {% endblock title %}

{% block css %} {% static 'css/register.css' %} {% endblock css %}

{% block content %}
{% include 'includes/header.html' %}

<!--Titulo de la pagina-->

<h1 class="title">Recuperar Cuenta</h1>

<!--Formulario para recuperar cuenta-->
    
<div class="container-form">
    <form class="form-register" method="post"> {% csrf_token %}
    
        <hr>
    
        <div class="form__container">
            <p>Ingrese su correo electrónico con el que abrió su cuenta.</p>
        </div>
        {{ form.non_field_errors }}
        <label class="form-register__label"><img src="{% static 'img/icono-contraseña.svg' %}" alt="icono-contraseña">
            {{form.email}}</label>


        <input class="form-register__input-submit" type="submit" value="Recuperar Cuenta">
    
        <hr>
    </form>
</div class="container-form">

{% include 'includes/footer.html' %}
{% endblock content %}

templates/users/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Login {% endblock title %}

{% block css %} {% static 'css/register.css' %} {% endblock css %}

{% block content %}
{% include 'includes/header.html' %}

 <!--Titulo de la pagina-->

 <h1 class="title">Inicio de Sesión</h1>

 <!-- Mensajes de exito o de error -->

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>  
    {% endfor %}
</ul>
{% endif %}

<!--Formulario de registro-->
    
<div class="container-form">
    <form class="form-register" method="post"> {% csrf_token %}
    
        <hr>
        {{ form.non_field_errors }}
        <div class="form__container">
            <h2>Iniciar Sesión</h2>
            <p>Llene los datos para iniciar sesión.</p>
        </div>
    
        <label class="form-register__label"><img src="{% static 'img/icono-user.svg' %}" alt="icono-user">
        {{form.email}}</label>

        <label class="form-register__label"><img src="{% static 'img/icono-contraseña.svg' %}" alt="icono-contraseña">
        {{form.password}}</label>

        {{form.captcha}}
    
        <input class="form-register__input-submit" type="submit">
    
        <div class="form__container-2">
            <p>No tienes una cuenta? <a href="{% url 'users_app:user_register' %}">Registrate</a></p>
        </div>

        <div class="form__container-2">
            <p><a href="{% url 'users_app:user_email_password' %}">¿Olvidaste tu Contraseña?</a></p>
        </div>
    
        <hr>
    </form>
</div class="container-form">

{% include 'includes/footer.html' %}
{% endblock content %}

templates/users/register.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Register {% endblock title %}

{% block css %} {% static 'css/register.css' %} {% endblock css %}

{% block content %}
{% include 'includes/header.html' %}

 <!--Titulo de la pagina-->

 <h1 class="title">Registro de Usuario</h1>

<!--Formulario de registro-->

<div class="container-form">
    <form class="form-register" method="post"> {% csrf_token %}

        <hr>

        <div class="form__container">
            <h2>Registrate</h2>
            <p>Por favor complete el formulario para crear una cuenta.</p>
        </div>
        {{form.error}}
        <label class="form-register__label">
            <img src="{% static 'img/icono-user.svg' %}" alt="icono-user">
            {{form.name}}
        </label>

        <label class="form-register__label">
            <img src=" {% static 'img/icono-user.svg' %}" alt="icono-user">
            {{form.last_name}}
        </label>

            {{form.email.errors}}
        <label class="form-register__label">
            <img src="{% static 'img/icono-correo.svg' %}" alt="icono-correo">
            {{form.email}}
        </label>
        
            {{form.password2.errors}}
        <label class="form-register__label">
            <img src="{% static 'img/icono-contraseña.svg' %}" alt="icono-contraseñá">
            {{form.password1}}
        </label>

        <label class="form-register__label">
            <img src="{% static 'img/icono-contraseña.svg' %}" alt="icono-contraseña">
            {{form.password2}}
        </label>
        {{form.captcha}}

        <input class="form-register__input-submit" type="submit" value="Registrar">

        <div class="form__container-2">
            <p>¿Ya tienes una cuenta? <a href="{% url 'users_app:user_login' %}">Inicia Sesión</a></p>
        </div>

        <hr>
    </form>
</div>

{% include 'includes/footer.html' %}
{% endblock content %}

templates/users/send-verification.html
<!DOCTYPE html>
<html>

<head>
    <title>Código de verificación</title>
    <style type="text/css">
        a {
            display: block;
            text-align: center;
        }

        img {
            width: fit-content;
            margin: 0 auto;
        }

        div {
            text-align: center;
            margin-top: 1.5em;
            background-color: #f5f5f5;
            padding: 1em;
            border-radius: 1em;
        }

        p {
            font-size: 1.5em;
            font-weight: 600;
        }

        h1 {
            margin-top: 1em;
            text-transform: uppercase;
            letter-spacing: 0.1em;
        }

        h2 {
            margin-top: 0.5em;
        }
    </style>
</head>

<body>
    <a href="https://fortuna303.com" target="_blank">
        <img src="https://fortuna303.com/static/img/logo.png" alt="logo">
    </a>
    <div>
        <p>{{ message_context }}</p>
        <h1>Código de verificación</h1>
        <h2>{{ validation_code }}</h2>
    </div>
</body>

</html>

templates/users/update-password.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Cambiar contraseña {% endblock title %}

{% block css %} {% static 'css/register.css' %} {% endblock css %}

{% block content %}
{% include 'includes/header.html' %}

<!--Titulo de la pagina-->

<h1 class="title">Cambiar contraseña</h1>

<!--Formulario de registro-->
    
<div class="container-form">
    <form class="form-register" method="post"> {% csrf_token %}
    
        <hr>
        {{ form.non_field_errors }}
        <div class="form__container">
            <p>Al cambiarla debera volver a iniciar sesión con su nueva 
                contraseñá.</p>
        </div>
        
        <label class="form-register__label"><img src="{% static 'img/icono-contraseña.svg' %}" alt="icono-contraseña">
            {{form.password3}}</label>

        {{form.password2.errors}}
        <label class="form-register__label"><img src="{% static 'img/icono-contraseña.svg' %}" alt="icono-contraseña">
            {{form.password1}}</label>

        <label class="form-register__label"><img src="{% static 'img/icono-contraseña.svg' %}" alt="icono-contraseña">
            {{form.password2}}</label>

        <input class="form-register__input-submit" type="submit" value="Actualizar">
    
        <hr>
    </form>
</div class="container-form">

{% include 'includes/footer.html' %}
{% endblock content %}